@baseUrl = http://localhost:3000
GET {{baseUrl}}/movies

### READ ALL FILTERED : Lire toutes les ressources de la collection selon le filtre donné
GET {{baseUrl}}/movies?minimum-duration=140

### READ ONE : Lire la ressource identifiée
GET {{baseUrl}}/movies/1


### CREATE ONE : Créer une ressource basée sur les données de la requête
POST {{baseUrl}}/movies
Content-Type: application/json

{
  "title": "Interstellar",
  "director": "Christopher Nolan",
  "duration": -169,
  "budget": -165,
  "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
  "imageUrl": "https://example.com/interstellar.jpg"
}


### READ ALL FILTERED : Lire toutes les ressources de la collection selon le filtre donné
GET {{baseUrl}}/movies?title-starts-with=the

### READ ALL SORT : Trier toutes les ressources de la collection selon le tri donné (Trier par titre en ordre décroissant)
GET {{baseUrl}}/movies?sortBy=title&sortOrder=desc

### READ ALL SORT : Trier toutes les ressources de la collection selon le tri donné (Trier par durée en ordre croissant)
GET {{baseUrl}}/movies?sortBy=duration&sortOrder=asc

### READ ALL SORT : Trier toutes les ressources de la collection selon le tri donné (Trier par titre en ordre croissant)
GET {{baseUrl}}/movies?sortBy=title&sortOrder=asc

### READ ALL SORT : Trier toutes les ressources de la collection selon le tri donné (Trier par durée en ordre décroissant)
GET {{baseUrl}}/movies?sortBy=duration&sortOrder=desc

### READ ALL SORT : Trier toutes les ressources de la collection selon le tri donné (Pour filtrer les films avec une durée minimale et trier par titre)
GET {{baseUrl}}/movies?minimum-duration=150&sortBy=title&sortOrder=desc
